import type { Question } from './types';

// Original prompts: 30 per category, with 10 easy, 10 medium, and 10 hard.
// Difficulty describes this question, not a player's ability or an IQ score.
export const QUESTIONS: Question[] = [
  {
    id: 'general-easy-01', category: 'general', difficulty: 'easy',
    prompt: 'Which planet in our Solar System has its orbit closest to the Sun?',
    options: ['Mars', 'Mercury', 'Venus', 'Jupiter'], correct: 1,
    explanation: 'Mercury is the innermost planet; Venus is the next planet outward.',
  },
  {
    id: 'general-easy-02', category: 'general', difficulty: 'easy',
    prompt: 'What is the name of a closed, flat shape with exactly three straight sides?',
    options: ['Square', 'Pentagon', 'Triangle', 'Hexagon'], correct: 2,
    explanation: 'A triangle has three straight sides and three vertices.',
  },
  {
    id: 'general-easy-03', category: 'general', difficulty: 'easy',
    prompt: 'Which human organ pumps blood through the circulatory system?',
    options: ['Heart', 'Stomach', 'Liver', 'Kidney'], correct: 0,
    explanation: 'The heart contracts to pump blood through blood vessels.',
  },
  {
    id: 'general-easy-04', category: 'general', difficulty: 'easy',
    prompt: 'At standard atmospheric pressure, at what Celsius temperature does pure water normally freeze?',
    options: ['100 °C', '10 °C', '−10 °C', '0 °C'], correct: 3,
    explanation: 'The normal freezing point of pure water is 0 °C at standard atmospheric pressure.',
  },
  {
    id: 'general-easy-05', category: 'general', difficulty: 'easy',
    prompt: 'How many minutes are in exactly three hours?',
    options: ['120', '180', '240', '90'], correct: 1,
    explanation: 'Each hour has 60 minutes, so 3 × 60 = 180 minutes.',
  },
  {
    id: 'general-easy-06', category: 'general', difficulty: 'easy',
    prompt: 'Which named ocean covers the greatest surface area on Earth?',
    options: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'], correct: 2,
    explanation: 'The Pacific Ocean is the largest ocean by surface area.',
  },
  {
    id: 'general-easy-07', category: 'general', difficulty: 'easy',
    prompt: 'Which gas from the air do human cells use in aerobic respiration to release energy from food?',
    options: ['Oxygen', 'Carbon dioxide', 'Helium', 'Neon'], correct: 0,
    explanation: 'Aerobic respiration uses oxygen to help release energy from food molecules.',
  },
  {
    id: 'general-easy-08', category: 'general', difficulty: 'easy',
    prompt: 'What is the usual name for the swimming, tailed young stage of a frog?',
    options: ['Cub', 'Foal', 'Chick', 'Tadpole'], correct: 3,
    explanation: 'A tadpole is the aquatic larval stage in the typical frog life cycle.',
  },
  {
    id: 'general-easy-09', category: 'general', difficulty: 'easy',
    prompt: 'In metric units, the prefix kilo- means multiplication by which number?',
    options: ['100', '1,000', '10,000', '10'], correct: 1,
    explanation: 'Kilo- means one thousand: one kilometre equals 1,000 metres.',
  },
  {
    id: 'general-easy-10', category: 'general', difficulty: 'easy',
    prompt: 'Which of these objects is the natural satellite that orbits Earth?',
    options: ['The Sun', 'Mars', 'The Moon', 'Venus'], correct: 2,
    explanation: 'The Moon is Earth\'s natural satellite. Earth itself orbits the Sun.',
  },
  {
    id: 'general-medium-01', category: 'general', difficulty: 'medium',
    prompt: 'Which chemical formula represents one molecule of water?',
    options: ['CO₂', 'O₂', 'H₂O', 'NaCl'], correct: 2,
    explanation: 'A water molecule contains two hydrogen atoms and one oxygen atom: H₂O.',
  },
  {
    id: 'general-medium-02', category: 'general', difficulty: 'medium',
    prompt: 'What is the change directly from a solid to a gas called?',
    options: ['Sublimation', 'Condensation', 'Freezing', 'Melting'], correct: 0,
    explanation: 'Sublimation changes a solid directly into a gas without a liquid stage.',
  },
  {
    id: 'general-medium-03', category: 'general', difficulty: 'medium',
    prompt: 'In standard anatomy, how many bones are counted in a typical adult human skeleton?',
    options: ['201', '206', '212', '226'], correct: 1,
    explanation: 'The standard count is 206 bones in a typical adult skeleton; individual variation can occur.',
  },
  {
    id: 'general-medium-04', category: 'general', difficulty: 'medium',
    prompt: 'On a flat Euclidean plane, what is the sum of a triangle\'s three interior angles?',
    options: ['90°', '120°', '360°', '180°'], correct: 3,
    explanation: 'The interior angles of a triangle on a Euclidean plane add to 180°.',
  },
  {
    id: 'general-medium-05', category: 'general', difficulty: 'medium',
    prompt: 'A spring is stretched within its elastic limit and held still. What kind of energy is stored by the stretch?',
    options: ['Chemical energy', 'Nuclear energy', 'Elastic potential energy', 'Kinetic energy'], correct: 2,
    explanation: 'Elastic deformation stores elastic potential energy, which can be released as the spring returns.',
  },
  {
    id: 'general-medium-06', category: 'general', difficulty: 'medium',
    prompt: 'Which instrument is designed to measure atmospheric pressure?',
    options: ['Thermometer', 'Barometer', 'Anemometer', 'Hygrometer'], correct: 1,
    explanation: 'A barometer measures air pressure; the other instruments measure temperature, wind speed, and humidity.',
  },
  {
    id: 'general-medium-07', category: 'general', difficulty: 'medium',
    prompt: 'What motion mainly produces the daily alternation of daylight and darkness at a place on Earth?',
    options: ['Earth rotating on its axis', 'Earth orbiting the Sun', 'The Moon changing phase', 'The Sun orbiting Earth'], correct: 0,
    explanation: 'As Earth rotates, a place turns toward the Sun and then away from it.',
  },
  {
    id: 'general-medium-08', category: 'general', difficulty: 'medium',
    prompt: 'Which unit measures area rather than length, volume, or time?',
    options: ['Metre', 'Litre', 'Second', 'Square metre'], correct: 3,
    explanation: 'Area measures two-dimensional extent, so its units include square metres.',
  },
  {
    id: 'general-medium-09', category: 'general', difficulty: 'medium',
    prompt: 'Under ordinary dry room conditions, which material is a good electrical conductor?',
    options: ['Rubber', 'Copper', 'Glass', 'Dry wood'], correct: 1,
    explanation: 'Copper is a metal with mobile electrons and is widely used to conduct electric current.',
  },
  {
    id: 'general-medium-10', category: 'general', difficulty: 'medium',
    prompt: 'What process lets green plants use light energy to make sugars from carbon dioxide and water?',
    options: ['Respiration', 'Condensation', 'Photosynthesis', 'Fermentation'], correct: 2,
    explanation: 'Photosynthesis captures light energy to build sugars from carbon dioxide and water.',
  },
  {
    id: 'general-hard-01', category: 'general', difficulty: 'hard',
    prompt: 'Which environment cannot carry an ordinary mechanical sound wave?',
    options: ['Steel', 'Seawater', 'Air', 'A vacuum'], correct: 3,
    explanation: 'Sound needs a material medium whose particles can vibrate; a vacuum has no such medium.',
  },
  {
    id: 'general-hard-02', category: 'general', difficulty: 'hard',
    prompt: 'What is the SI base unit of electric current?',
    options: ['Ampere', 'Volt', 'Watt', 'Ohm'], correct: 0,
    explanation: 'Current is measured in amperes. Volts measure potential difference, watts power, and ohms resistance.',
  },
  {
    id: 'general-hard-03', category: 'general', difficulty: 'hard',
    prompt: 'Why does ordinary freshwater ice float in liquid freshwater near its freezing point?',
    options: ['Ice always has greater total mass', 'Ice has greater density', 'Ice has lower density', 'Ice is held up by magnetism'], correct: 2,
    explanation: 'Water expands when it forms ordinary ice, making the ice less dense than the surrounding liquid water.',
  },
  {
    id: 'general-hard-04', category: 'general', difficulty: 'hard',
    prompt: 'Why does water in an open pot usually boil at a lower temperature high on a mountain than at sea level?',
    options: ['Gravity is much stronger there', 'Atmospheric pressure is lower there', 'All mountain water contains more salt', 'Water receives less sunlight there'], correct: 1,
    explanation: 'Boiling occurs when vapour pressure matches external pressure; lower atmospheric pressure lowers the boiling temperature.',
  },
  {
    id: 'general-hard-05', category: 'general', difficulty: 'hard',
    prompt: 'Comparing blue light with red light in a vacuum, which has the shorter wavelength?',
    options: ['Blue light', 'Red light', 'Both have the same wavelength', 'Neither has a wavelength'], correct: 0,
    explanation: 'Blue light has a shorter wavelength and a higher frequency than red light.',
  },
  {
    id: 'general-hard-06', category: 'general', difficulty: 'hard',
    prompt: 'What chiefly causes Earth\'s Northern and Southern Hemispheres to have opposite seasons?',
    options: ['A large seasonal change in Earth\'s mass', 'The Moon blocking sunlight', 'Earth\'s axial tilt as it orbits the Sun', 'The Sun orbiting each hemisphere'], correct: 2,
    explanation: 'Earth\'s tilted axis makes each hemisphere receive different sunlight angles and day lengths over the year.',
  },
  {
    id: 'general-hard-07', category: 'general', difficulty: 'hard',
    prompt: 'An electrically neutral atom contains 17 protons. How many electrons does it contain?',
    options: ['8', '16', '18', '17'], correct: 3,
    explanation: 'Neutral atoms have equal numbers of positive protons and negative electrons, so this atom has 17 electrons.',
  },
  {
    id: 'general-hard-08', category: 'general', difficulty: 'hard',
    prompt: 'Two lamps are on separate parallel branches of an ideal battery. One branch is opened. What happens to the other lamp?',
    options: ['It must go out', 'It stays lit at the same battery voltage', 'Its current must reverse', 'Its voltage must double'], correct: 1,
    explanation: 'Each parallel branch has its own complete path across the battery. Opening one does not break the other.',
  },
  {
    id: 'general-hard-09', category: 'general', difficulty: 'hard',
    prompt: 'Ignoring official time zones, places 180° apart in longitude differ in local mean solar time by how many hours?',
    options: ['12 hours', '6 hours', '18 hours', '24 hours'], correct: 0,
    explanation: '360° corresponds to 24 hours of mean solar time; 180° is half of that, or 12 hours.',
  },
  {
    id: 'general-hard-10', category: 'general', difficulty: 'hard',
    prompt: 'A solution at pH 3 has how many times the hydrogen-ion activity of a solution at pH 5?',
    options: ['2 times', '10 times', '100 times', '1,000 times'], correct: 2,
    explanation: 'Each one-unit fall in pH means ten times the hydrogen-ion activity. Two units mean 10 × 10 = 100 times.',
  },
  {
    id: 'puzzles-easy-01', category: 'puzzles', difficulty: 'easy',
    prompt: 'Three notebooks cost $4 each, with no extra fees. You pay $20. How much change should you receive?',
    options: ['$4', '$6', '$8', '$12'], correct: 2,
    explanation: 'The notebooks cost 3 × $4 = $12, leaving $20 − $12 = $8 in change.',
  },
  {
    id: 'puzzles-easy-02', category: 'puzzles', difficulty: 'easy',
    prompt: 'A recipe uses 2 cups of rice for 4 equal servings. How many cups make 8 servings of the same size?',
    options: ['4 cups', '3 cups', '6 cups', '8 cups'], correct: 0,
    explanation: 'Eight servings are twice four servings, so double the rice: 2 × 2 = 4 cups.',
  },
  {
    id: 'puzzles-easy-03', category: 'puzzles', difficulty: 'easy',
    prompt: 'A bus leaves at 09:20 and the journey takes exactly 35 minutes. What is its arrival time that morning?',
    options: ['09:45', '09:55', '10:05', '10:15'], correct: 1,
    explanation: 'Adding 35 minutes to 09:20 gives 09:55.',
  },
  {
    id: 'puzzles-easy-04', category: 'puzzles', difficulty: 'easy',
    prompt: 'A shop packs 24 apples into bags containing exactly 6 apples each. How many full bags does it make?',
    options: ['2', '3', '6', '4'], correct: 3,
    explanation: '24 apples ÷ 6 apples per bag = 4 full bags.',
  },
  {
    id: 'puzzles-easy-05', category: 'puzzles', difficulty: 'easy',
    prompt: 'A person walks a 180-metre path at a constant 60 metres per minute, without stopping. How long does it take?',
    options: ['3 minutes', '2 minutes', '4 minutes', '6 minutes'], correct: 0,
    explanation: 'Time = distance ÷ speed = 180 ÷ 60 = 3 minutes.',
  },
  {
    id: 'puzzles-easy-06', category: 'puzzles', difficulty: 'easy',
    prompt: 'A bottle contains 1 litre of water. After 250 millilitres are poured out, how much remains?',
    options: ['250 millilitres', '500 millilitres', '750 millilitres', '850 millilitres'], correct: 2,
    explanation: '1 litre = 1,000 millilitres; 1,000 − 250 = 750 millilitres remain.',
  },
  {
    id: 'puzzles-easy-07', category: 'puzzles', difficulty: 'easy',
    prompt: 'A rectangular garden is 6 metres long and 4 metres wide. What length of fence encloses all four sides with no gaps?',
    options: ['10 metres', '20 metres', '24 metres', '28 metres'], correct: 1,
    explanation: 'The perimeter is 2 × (6 + 4) = 20 metres.',
  },
  {
    id: 'puzzles-easy-08', category: 'puzzles', difficulty: 'easy',
    prompt: 'Potatoes cost $3 per kilogram, with no extra fees. What is the price of exactly 2 kilograms?',
    options: ['$3', '$4', '$5', '$6'], correct: 3,
    explanation: '2 kilograms × $3 per kilogram = $6.',
  },
  {
    id: 'puzzles-easy-09', category: 'puzzles', difficulty: 'easy',
    prompt: 'A printer completes 6 identical posters per hour at a steady rate. How long does it need for 18 posters, with no setup time?',
    options: ['1 hour', '2 hours', '3 hours', '4 hours'], correct: 2,
    explanation: '18 posters ÷ 6 posters per hour = 3 hours.',
  },
  {
    id: 'puzzles-easy-10', category: 'puzzles', difficulty: 'easy',
    prompt: 'A room has 30 seats. Exactly 22 are occupied, one person per seat. How many seats are empty?',
    options: ['8', '6', '10', '12'], correct: 0,
    explanation: '30 seats − 22 occupied seats = 8 empty seats.',
  },
  {
    id: 'puzzles-medium-01', category: 'puzzles', difficulty: 'medium',
    prompt: 'An $80 jacket is discounted by 25%, with no tax or fees added. What is the sale price?',
    options: ['$55', '$60', '$65', '$75'], correct: 1,
    explanation: '25% of $80 is $20; $80 − $20 = $60.',
  },
  {
    id: 'puzzles-medium-02', category: 'puzzles', difficulty: 'medium',
    prompt: 'A train covers 150 kilometres in exactly 2.5 hours. What is its average speed for the whole journey?',
    options: ['50 km/h', '55 km/h', '75 km/h', '60 km/h'], correct: 3,
    explanation: 'Average speed = total distance ÷ total time = 150 ÷ 2.5 = 60 km/h.',
  },
  {
    id: 'puzzles-medium-03', category: 'puzzles', difficulty: 'medium',
    prompt: 'Each baking tray holds at most 12 muffins. What is the minimum number of trays needed to hold 50 muffins at once?',
    options: ['3', '4', '5', '6'], correct: 2,
    explanation: 'Four trays hold only 48 muffins, so a fifth tray is needed for the remaining two.',
  },
  {
    id: 'puzzles-medium-04', category: 'puzzles', difficulty: 'medium',
    prompt: 'A tank starts with 10 litres. Water enters at 3 litres per minute and leaves at 1 litre per minute, both steadily. With no overflow, how much is in it after 8 minutes?',
    options: ['26 litres', '24 litres', '30 litres', '34 litres'], correct: 0,
    explanation: 'The net gain is 3 − 1 = 2 litres per minute. 10 + 8 × 2 = 26 litres.',
  },
  {
    id: 'puzzles-medium-05', category: 'puzzles', difficulty: 'medium',
    prompt: 'A 3-metre by 2-metre floor is covered by square tiles with 0.5-metre sides. With no gaps, overlap, or cutting loss, how many tiles are needed?',
    options: ['6', '12', '18', '24'], correct: 3,
    explanation: 'There are 3 ÷ 0.5 = 6 tiles along one side and 2 ÷ 0.5 = 4 along the other: 6 × 4 = 24.',
  },
  {
    id: 'puzzles-medium-06', category: 'puzzles', difficulty: 'medium',
    prompt: 'Three friends split a $54 bill equally after a single $6 discount on the whole bill. With no further charges, how much does each pay?',
    options: ['$14', '$16', '$18', '$20'], correct: 1,
    explanation: 'The discounted total is $54 − $6 = $48. Dividing by three gives $16 each.',
  },
  {
    id: 'puzzles-medium-07', category: 'puzzles', difficulty: 'medium',
    prompt: 'A meeting starts at 14:40 and lasts 1 hour 45 minutes without a break. When does it finish on the same day?',
    options: ['15:25', '16:15', '16:25', '16:45'], correct: 2,
    explanation: '14:40 + 1 hour = 15:40; another 45 minutes gives 16:25.',
  },
  {
    id: 'puzzles-medium-08', category: 'puzzles', difficulty: 'medium',
    prompt: 'Mix 2 litres of juice with 3 litres of water, assuming volumes add. In a well-mixed 500-millilitre serving, how much is juice?',
    options: ['200 millilitres', '250 millilitres', '300 millilitres', '100 millilitres'], correct: 0,
    explanation: 'Juice is 2/5 of the mixture. 500 × 2/5 = 200 millilitres.',
  },
  {
    id: 'puzzles-medium-09', category: 'puzzles', difficulty: 'medium',
    prompt: 'A parcel may weigh at most 2.4 kilograms. Its empty box weighs 0.6 kilograms and each book weighs 0.3 kilograms. With nothing else packed, how many books fit within the limit?',
    options: ['4', '5', '6', '8'], correct: 2,
    explanation: 'The books may weigh 2.4 − 0.6 = 1.8 kilograms. 1.8 ÷ 0.3 = 6 books.',
  },
  {
    id: 'puzzles-medium-10', category: 'puzzles', difficulty: 'medium',
    prompt: 'One can of paint covers exactly 12 square metres with one coat. What is the fewest whole cans needed for one coat on 30 square metres, with no waste?',
    options: ['2', '3', '4', '5'], correct: 1,
    explanation: '30 ÷ 12 = 2.5 cans of paint, so buying whole cans requires rounding up to 3.',
  },
  {
    id: 'puzzles-hard-01', category: 'puzzles', difficulty: 'hard',
    prompt: 'A $200 item receives a 20% discount, then a further 10% discount on the reduced price. With no extra charges, what is the final price?',
    options: ['$140', '$142', '$144', '$160'], correct: 2,
    explanation: 'After the first discount: $200 × 0.8 = $160. Then $160 × 0.9 = $144.',
  },
  {
    id: 'puzzles-hard-02', category: 'puzzles', difficulty: 'hard',
    prompt: 'One worker can finish a task in 6 hours and another in 3 hours. They work together from the start at constant, additive rates without interference. How long does the task take?',
    options: ['2 hours', '3 hours', '4.5 hours', '9 hours'], correct: 0,
    explanation: 'Their combined rate is 1/6 + 1/3 = 1/2 of the task per hour, so the whole task takes 2 hours.',
  },
  {
    id: 'puzzles-hard-03', category: 'puzzles', difficulty: 'hard',
    prompt: 'An empty 48-litre tank has a steady 5-litre-per-minute inlet and a pump removing 2 litres per minute from the start. How long until the tank first becomes full?',
    options: ['10 minutes', '16 minutes', '24 minutes', '48 minutes'], correct: 1,
    explanation: 'The net filling rate is 5 − 2 = 3 litres per minute. 48 ÷ 3 = 16 minutes.',
  },
  {
    id: 'puzzles-hard-04', category: 'puzzles', difficulty: 'hard',
    prompt: 'Two cyclists leave the same point at the same time in opposite directions on a straight road, at constant speeds of 9 and 15 km/h. When will they be 48 kilometres apart?',
    options: ['0.5 hours', '1 hour', '1.5 hours', '2 hours'], correct: 3,
    explanation: 'Their separation grows at 9 + 15 = 24 km/h. 48 ÷ 24 = 2 hours.',
  },
  {
    id: 'puzzles-hard-05', category: 'puzzles', difficulty: 'hard',
    prompt: 'Four tests count equally toward an average. The first three scores are 70, 80, and 90. What fourth score gives an average of 85?',
    options: ['85', '90', '100', '110'], correct: 2,
    explanation: 'Four scores must total 4 × 85 = 340. The first three total 240, so the fourth must be 100.',
  },
  {
    id: 'puzzles-hard-06', category: 'puzzles', difficulty: 'hard',
    prompt: 'Rental A costs $20 plus $0.50 per kilometre. Rental B costs $8 plus $0.80 per kilometre, with no other charges. At what distance do they cost the same?',
    options: ['40 kilometres', '24 kilometres', '60 kilometres', '80 kilometres'], correct: 0,
    explanation: 'The fixed-fee difference is $12 and the per-kilometre difference is $0.30. $12 ÷ $0.30 = 40 kilometres.',
  },
  {
    id: 'puzzles-hard-07', category: 'puzzles', difficulty: 'hard',
    prompt: 'A shop mixes 2 kilograms of nuts costing $6 per kilogram with 3 kilograms costing $10 per kilogram. With no loss or extra costs, what is the mixture\'s cost per kilogram?',
    options: ['$7.60', '$8.00', '$8.60', '$8.40'], correct: 3,
    explanation: 'The total cost is 2 × $6 + 3 × $10 = $42 for 5 kilograms. $42 ÷ 5 = $8.40 per kilogram.',
  },
  {
    id: 'puzzles-hard-08', category: 'puzzles', difficulty: 'hard',
    prompt: 'A machine starts with no finished parts and completes batches of 5 parts every 4 minutes. There is no setup time or pause between batches. When are 45 parts first ready?',
    options: ['32 minutes', '36 minutes', '40 minutes', '45 minutes'], correct: 1,
    explanation: '45 ÷ 5 = 9 batches. Nine batches at 4 minutes each take 36 minutes.',
  },
  {
    id: 'puzzles-hard-09', category: 'puzzles', difficulty: 'hard',
    prompt: 'A stall pays $180 in fixed costs. Each item costs $18 to make and sells for $30. With no other costs and all made items sold, how many sales exactly cover all costs?',
    options: ['6', '10', '15', '20'], correct: 2,
    explanation: 'Each sale contributes $30 − $18 = $12 toward fixed costs. $180 ÷ $12 = 15 sales to break even.',
  },
  {
    id: 'puzzles-hard-10', category: 'puzzles', difficulty: 'hard',
    prompt: 'An 8-metre by 6-metre rectangular garden has a 1-metre-wide path entirely inside all four edges. What is the total area of the path, counting corners only once?',
    options: ['24 square metres', '26 square metres', '28 square metres', '32 square metres'], correct: 0,
    explanation: 'The garden area is 8 × 6 = 48. The inner rectangle is (8 − 2) × (6 − 2) = 24. The path is 48 − 24 = 24 square metres.',
  },
  {
    id: 'reasoning-easy-01', category: 'reasoning', difficulty: 'easy',
    prompt: 'A sequence adds 3 at every step: 4, 7, 10, 13. What is the next number?',
    options: ['15', '16', '17', '18'], correct: 1,
    explanation: 'Continue the stated rule: 13 + 3 = 16.',
  },
  {
    id: 'reasoning-easy-02', category: 'reasoning', difficulty: 'easy',
    prompt: 'Each number is double the previous one: 3, 6, 12, 24. What comes next?',
    options: ['30', '36', '42', '48'], correct: 3,
    explanation: 'Doubling the last number gives 24 × 2 = 48.',
  },
  {
    id: 'reasoning-easy-03', category: 'reasoning', difficulty: 'easy',
    prompt: 'Maya is a 9-year-old girl. Her brother is exactly 14 years old at the same time. How many years older is her brother?',
    options: ['5 years', '4 years', '6 years', '7 years'], correct: 0,
    explanation: 'The difference is 14 − 9 = 5 years.',
  },
  {
    id: 'reasoning-easy-04', category: 'reasoning', difficulty: 'easy',
    prompt: 'Leo is a boy and Priya\'s only child. Priya is his mother, and Nila is Priya\'s mother. Through Priya, how is Nila related to Leo?',
    options: ['Aunt', 'Sister', 'Maternal grandmother', 'Cousin'], correct: 2,
    explanation: 'Nila is the mother of Leo\'s mother, so she is his maternal grandmother.',
  },
  {
    id: 'reasoning-easy-05', category: 'reasoning', difficulty: 'easy',
    prompt: 'Ava is a girl and Ben\'s only child. Ben is her father. How is Ava related to Ben?',
    options: ['Son', 'Daughter', 'Sister', 'Mother'], correct: 1,
    explanation: 'A female child is a daughter, so Ava is Ben\'s daughter.',
  },
  {
    id: 'reasoning-easy-06', category: 'reasoning', difficulty: 'easy',
    prompt: 'A sequence subtracts 4 at every step: 30, 26, 22, 18. What is the next number?',
    options: ['14', '12', '16', '10'], correct: 0,
    explanation: 'Apply the stated rule again: 18 − 4 = 14.',
  },
  {
    id: 'reasoning-easy-07', category: 'reasoning', difficulty: 'easy',
    prompt: 'Nia is exactly 8 years old today. How old will Nia be exactly 6 years from today?',
    options: ['12 years', '13 years', '16 years', '14 years'], correct: 3,
    explanation: 'Six more years gives 8 + 6 = 14 years old.',
  },
  {
    id: 'reasoning-easy-08', category: 'reasoning', difficulty: 'easy',
    prompt: 'Repeat the three-shape cycle circle, square, triangle. The list so far is circle, square, triangle, circle, square. Which shape is next?',
    options: ['Circle', 'Square', 'Triangle', 'Star'], correct: 2,
    explanation: 'Each cycle ends with a triangle, so a triangle follows the second square.',
  },
  {
    id: 'reasoning-easy-09', category: 'reasoning', difficulty: 'easy',
    prompt: 'Omar is taller than Pia, and Pia is taller than Rui. Who is the shortest of these three people?',
    options: ['Omar', 'Rui', 'Pia', 'All three are the same height'], correct: 1,
    explanation: 'Their heights decrease in the order Omar, Pia, Rui, making Rui the shortest.',
  },
  {
    id: 'reasoning-easy-10', category: 'reasoning', difficulty: 'easy',
    prompt: 'Starting from 2, a sequence repeatedly adds 5: 2, 7, 12, 17. Which number comes next?',
    options: ['22', '21', '25', '27'], correct: 0,
    explanation: 'The next step is 17 + 5 = 22.',
  },
  {
    id: 'reasoning-medium-01', category: 'reasoning', difficulty: 'medium',
    prompt: 'Sisters Ada and Bea have ages totalling exactly 30 years. Ada is exactly 6 years older than Bea. How old is Bea?',
    options: ['10 years', '11 years', '12 years', '18 years'], correct: 2,
    explanation: 'If Bea is b, Ada is b + 6. Then 2b + 6 = 30, so b = 12.',
  },
  {
    id: 'reasoning-medium-02', category: 'reasoning', difficulty: 'medium',
    prompt: 'A mother is exactly 36 years old and her daughter is exactly 12. In how many years will the mother be exactly twice the daughter\'s age?',
    options: ['6 years', '12 years', '18 years', '24 years'], correct: 1,
    explanation: 'Solve 36 + t = 2(12 + t): t = 12. Their ages will then be 48 and 24.',
  },
  {
    id: 'reasoning-medium-03', category: 'reasoning', difficulty: 'medium',
    prompt: 'To get the next number, multiply by 3 and then add 1: 2, 7, 22, 67. What comes next?',
    options: ['134', '200', '201', '202'], correct: 3,
    explanation: 'Apply the rule to 67: 67 × 3 + 1 = 201 + 1 = 202.',
  },
  {
    id: 'reasoning-medium-04', category: 'reasoning', difficulty: 'medium',
    prompt: 'Starting at 1, add successive even numbers 2, 4, 6, 8, 10, and so on. The sequence is 1, 3, 7, 13, 21. What comes next?',
    options: ['31', '29', '30', '33'], correct: 0,
    explanation: 'The additions so far are 2, 4, 6, and 8. The next addition is 10, so 21 + 10 = 31.',
  },
  {
    id: 'reasoning-medium-05', category: 'reasoning', difficulty: 'medium',
    prompt: 'Evan is a boy with no siblings. His mother Lila has exactly one sister, Mara. Through Lila, how is Mara related to Evan?',
    options: ['Grandmother', 'Cousin', 'Maternal aunt', 'Sister'], correct: 2,
    explanation: 'A mother\'s sister is a maternal aunt, so Mara is Evan\'s maternal aunt.',
  },
  {
    id: 'reasoning-medium-06', category: 'reasoning', difficulty: 'medium',
    prompt: 'Zoe is a girl and Amir\'s only child. Amir is Zoe\'s father, and Hugo is Amir\'s father. Through Amir, how is Hugo related to Zoe?',
    options: ['Uncle', 'Paternal grandfather', 'Brother', 'Nephew'], correct: 1,
    explanation: 'Hugo is the father of Zoe\'s father, making him her paternal grandfather.',
  },
  {
    id: 'reasoning-medium-07', category: 'reasoning', difficulty: 'medium',
    prompt: 'Exactly four runners finish without ties. Liv finishes before Mo, Mo before Ned, and Ned before Ola. Who finishes third?',
    options: ['Mo', 'Liv', 'Ola', 'Ned'], correct: 3,
    explanation: 'The complete order is Liv, Mo, Ned, Ola. Ned is third.',
  },
  {
    id: 'reasoning-medium-08', category: 'reasoning', difficulty: 'medium',
    prompt: 'A sequence alternates adding 5 and subtracting 2, starting with an addition: 10, 15, 13, 18, 16. What comes next?',
    options: ['21', '20', '23', '18'], correct: 0,
    explanation: 'The last step subtracted 2, so the next adds 5: 16 + 5 = 21.',
  },
  {
    id: 'reasoning-medium-09', category: 'reasoning', difficulty: 'medium',
    prompt: 'A brother is exactly 24 years old and his sister is exactly 18. How old was the sister when the brother was exactly 18?',
    options: ['6 years', '10 years', '12 years', '14 years'], correct: 2,
    explanation: 'The brother was 18 six years ago. His sister was then 18 − 6 = 12.',
  },
  {
    id: 'reasoning-medium-10', category: 'reasoning', difficulty: 'medium',
    prompt: 'All blue tokens are round. No round tokens are wooden. Which statement must follow from these rules?',
    options: ['All round tokens are blue', 'No blue tokens are wooden', 'All wooden tokens are blue', 'Some blue tokens are wooden'], correct: 1,
    explanation: 'Every blue token is round, and being round excludes being wooden. Therefore no blue token can be wooden.',
  },
  {
    id: 'reasoning-hard-01', category: 'reasoning', difficulty: 'hard',
    prompt: 'A father is exactly four times his son\'s age now. In 12 years, the father will be exactly twice his son\'s age. How old is the son now?',
    options: ['4 years', '8 years', '6 years', '12 years'], correct: 2,
    explanation: 'Let the son be s. Then 4s + 12 = 2(s + 12), giving 2s = 12 and s = 6.',
  },
  {
    id: 'reasoning-hard-02', category: 'reasoning', difficulty: 'hard',
    prompt: 'Three sisters have ages totalling exactly 44 years. The middle sister is 3 years older than the youngest, and the oldest is 8 years older than the youngest. How old is the oldest?',
    options: ['19 years', '20 years', '21 years', '22 years'], correct: 0,
    explanation: 'Let the youngest be x. Then x + (x + 3) + (x + 8) = 44, so x = 11. The oldest is 11 + 8 = 19.',
  },
  {
    id: 'reasoning-hard-03', category: 'reasoning', difficulty: 'hard',
    prompt: 'A mother is exactly 40 years old. Her only children are twin daughters, each exactly 10. In how many years will the mother\'s age equal the sum of her daughters\' ages?',
    options: ['5 years', '10 years', '15 years', '20 years'], correct: 3,
    explanation: 'Solve 40 + t = (10 + t) + (10 + t). This gives t = 20, when the ages are 60, 30, and 30.',
  },
  {
    id: 'reasoning-hard-04', category: 'reasoning', difficulty: 'hard',
    prompt: 'Elena is a girl and her mother Nora\'s only child. Nora and Paul are full siblings. Paul is the father of a boy, Sam, his only child. Through Nora and Paul, how are Elena and Sam related?',
    options: ['Siblings', 'First cousins', 'Aunt and nephew', 'Grandmother and grandson'], correct: 1,
    explanation: 'Their parents are siblings. Children of siblings are first cousins through those parents.',
  },
  {
    id: 'reasoning-hard-05', category: 'reasoning', difficulty: 'hard',
    prompt: 'Rosa is a woman whose only child is Inez, a woman. Inez\'s only child is Joel, a man. Joel\'s only child is Tara, a girl. Through this parent-child chain, what is Rosa to Tara?',
    options: ['Mother', 'Grandmother', 'Great-grandmother', 'Aunt'], correct: 2,
    explanation: 'Joel is Tara\'s father, Inez is her grandmother, and Rosa is one generation further back: her great-grandmother.',
  },
  {
    id: 'reasoning-hard-06', category: 'reasoning', difficulty: 'hard',
    prompt: 'Odd positions follow 2, 4, 6, 8, ... and even positions follow 9, 12, 15, 18, .... In 2, 9, 4, 12, 6, 15, 8, what is the next number?',
    options: ['18', '16', '17', '21'], correct: 0,
    explanation: 'The next position is the eighth, an even position. The even-position values increase by 3: 9, 12, 15, 18.',
  },
  {
    id: 'reasoning-hard-07', category: 'reasoning', difficulty: 'hard',
    prompt: 'Starting at 3, repeatedly multiply the previous value by 2 and subtract 1: 3, 5, 9, 17, 33. What comes next?',
    options: ['64', '66', '68', '65'], correct: 3,
    explanation: 'The next value is 33 × 2 − 1 = 66 − 1 = 65.',
  },
  {
    id: 'reasoning-hard-08', category: 'reasoning', difficulty: 'hard',
    prompt: 'Use the digits 1, 2, 3, and 4 exactly once each to make a four-digit even number. How many such numbers have a first digit greater than their second digit?',
    options: ['4', '6', '8', '12'], correct: 1,
    explanation: 'The last digit is 2 or 4. For each choice, the remaining three digits have 6 orders, exactly 3 with the first greater than the second. Total: 2 × 3 = 6.',
  },
  {
    id: 'reasoning-hard-09', category: 'reasoning', difficulty: 'hard',
    prompt: 'Exactly five people stand in a line, with before meaning nearer the front. Asha is immediately before Ben, and Ben immediately before Chen. Davi is before Asha, and Esme is after Chen. Who is in the middle?',
    options: ['Asha', 'Chen', 'Ben', 'Davi'], correct: 2,
    explanation: 'The only order is Davi, Asha, Ben, Chen, Esme. The third person, Ben, is in the middle.',
  },
  {
    id: 'reasoning-hard-10', category: 'reasoning', difficulty: 'hard',
    prompt: 'A two-digit whole number has digits adding to 11. Reversing its digits makes a number exactly 27 greater. What is the original number?',
    options: ['38', '56', '65', '47'], correct: 3,
    explanation: 'If the tens digit is a and the units digit b, then a + b = 11 and 9(b − a) = 27. Thus b − a = 3, giving a = 4 and b = 7: 47.',
  },
];